# Generated by Django 2.0.5 on 2018-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('name_client', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
